services:
  - type: web
    name: gospelvibes
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn MusicPlayer.wsgi:application
    pythonVersion: 3.11.8
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: MusicPlayer.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
    staticPublishPath: staticfiles